server:
  port: 3131
spring:
  jpa:
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: db/changelog/changelog.yaml
    default-schema: ${DB_SCHEMA}